GET http://localhost:3000/users

### create a new campaign

POST http://localhost:3000/campaigns
Content-Type: application/json

{
  "name": "Summer Sale 50% Off",
  "content": "Up to 50% off on all summer items",
  "contacts": [
    "contact1@example.com",
    "contact2@example.com"
  ]
}